--USAR ESTA OPCION SI SE QUIERE VER EL DASHBOARD SIN TENER QUE AÑADIR REGISTROS MANUALMENTE Y CLASIFICARLOS
-- Tablas y datos de muestra.


-- Módulo Registros
CREATE TABLE origen_datos (
    id_origen_datos   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              INTEGER NOT NULL CHECK (tipo IN (0, 1)),
    nombre            VARCHAR(100) NOT NULL,
    UNIQUE (tipo, nombre)
);

CREATE TABLE registro (
    id_registro       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha             TIMESTAMPTZ NOT NULL,
    ip_origen         VARCHAR(45) NOT NULL,
    ip_destino        VARCHAR(45),
    datos             JSONB NOT NULL,
    estado            INTEGER NOT NULL,
    id_origen_datos   INTEGER NOT NULL,
    hash_registro     VARCHAR(64) NOT NULL UNIQUE,


    CONSTRAINT fk_registro_origen_datos
        FOREIGN KEY (id_origen_datos)
        REFERENCES origen_datos(id_origen_datos)
        ON DELETE RESTRICT
);

CREATE TABLE clasificacion (
    id_clasificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro       INTEGER NOT NULL UNIQUE,
    tipo_trafico      INTEGER NOT NULL,
    justificacion     TEXT NOT NULL,

    CONSTRAINT fk_clasificacion_registro
        FOREIGN KEY (id_registro)
        REFERENCES registro(id_registro)
        ON DELETE CASCADE
);


-- Módulo Usuarios
CREATE TABLE usuario (
    id_usuario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(100) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    hash_contrasena   VARCHAR(255) NOT NULL
);


-- Origen de datos
INSERT INTO origen_datos (id_origen_datos, tipo, nombre) VALUES
    (1, 0, 'IoT-23');


-- Registros del dataset IoT-23 (CTU-IoT-Malware-Capture-1-1)
INSERT INTO registro (id_registro, fecha, ip_origen, ip_destino, datos, estado, id_origen_datos, hash_registro) VALUES
    (1,  '2019-01-10 20:06:29+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"CzsY0D4B96NTr8m7ld","proto":"tcp","service":"http","duration":1.686784,"orig_bytes":149,"resp_bytes":171750,"conn_state":"SF","history":"ShADadttfF","orig_pkts":122,"resp_pkts":122}',
     1, 1, 'hash_registro_1'),

    (2,  '2019-01-10 20:06:31+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"CGEJbl3RNkmXzmkEd4","proto":"tcp","duration":3.081233,"orig_bytes":0,"resp_bytes":0,"conn_state":"S0","history":"S","orig_pkts":3,"resp_pkts":0}',
     1, 1, 'hash_registro_2'),

    (3,  '2019-01-10 20:06:51+00', '192.168.1.199', '94.124.107.190',
     '{"uid":"C6geJBDrugw5zVZSd","proto":"udp","service":"ntp","duration":0.007489,"orig_bytes":48,"resp_bytes":48,"conn_state":"SF","history":"Dd","orig_pkts":1,"resp_pkts":1}',
     1, 1, 'hash_registro_3'),

    (4,  '2019-01-10 20:07:03+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"CBjcNy4pOh8Xg1H4S","proto":"tcp","service":"http","duration":1.847943,"orig_bytes":149,"resp_bytes":171878,"conn_state":"SF","history":"ShADadttfF","orig_pkts":102,"resp_pkts":121}',
     1, 1, 'hash_registro_4'),

    (5,  '2019-01-10 20:07:26+00', '192.168.1.199', '81.2.248.189',
     '{"uid":"CHWVdb4BKoO7wivXMc","proto":"udp","service":"ntp","duration":0.005247,"orig_bytes":48,"resp_bytes":48,"conn_state":"SF","history":"Dd","orig_pkts":1,"resp_pkts":1}',
     1, 1, 'hash_registro_5'),

    (6,  '2019-01-10 20:07:30+00', '192.168.1.199', '77.78.107.252',
     '{"uid":"C5ADtL388Ib8fAyMXg","proto":"udp","service":"ntp","duration":0.002245,"orig_bytes":48,"resp_bytes":48,"conn_state":"SF","history":"Dd","orig_pkts":1,"resp_pkts":1}',
     1, 1, 'hash_registro_6'),

    (7,  '2019-01-10 20:08:48+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"CVNQP5iuWtYHzOkEj","proto":"tcp","service":"http","duration":1.185313,"orig_bytes":149,"resp_bytes":137844,"conn_state":"SF","history":"ShADadttfF","orig_pkts":99,"resp_pkts":99}',
     1, 1, 'hash_registro_7'),

    (8,  '2019-01-10 20:09:24+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"C4S1Kz40sipbEERa76","proto":"tcp","service":"http","duration":1.531888,"orig_bytes":149,"resp_bytes":139570,"conn_state":"SF","history":"ShADadttfF","orig_pkts":100,"resp_pkts":99}',
     1, 1, 'hash_registro_8'),

    (9,  '2019-01-10 20:08:50+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"CvTcwH1QzC4b2uSCnf","proto":"tcp","service":"http","duration":1.43868,"orig_bytes":148,"resp_bytes":121390,"conn_state":"SF","history":"ShADadttfF","orig_pkts":92,"resp_pkts":92}',
     0, 1, 'hash_registro_9'),

    (10, '2019-01-10 20:09:25+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"C2Lnmo1m6gOEF5Flyj","proto":"tcp","service":"http","duration":1.612322,"orig_bytes":147,"resp_bytes":152039,"conn_state":"SF","history":"ShADadttfF","orig_pkts":103,"resp_pkts":108}',
     0, 1, 'hash_registro_10'),

    (11, '2019-01-10 20:09:27+00', '192.168.1.199', '46.101.251.172',
     '{"uid":"C0aWOD1sg4rINDNIN7","proto":"tcp","service":"http","duration":2.295936,"orig_bytes":150,"resp_bytes":149980,"conn_state":"SF","history":"ShADadttfF","orig_pkts":108,"resp_pkts":107}',
     0, 1, 'hash_registro_11'),

    (12, '2019-01-10 20:10:24+00', '192.168.1.199', '45.32.4.67',
     '{"uid":"C0fbksytDcSiHFb92","proto":"udp","service":"ntp","duration":0.126928,"orig_bytes":48,"resp_bytes":48,"conn_state":"SF","history":"Dd","orig_pkts":1,"resp_pkts":1}',
     2, 1, 'hash_registro_12');


-- Clasificaciones
INSERT INTO clasificacion (id_clasificacion, id_registro, tipo_trafico, justificacion) VALUES
    (1, 1, 3,
     'Conexión HTTP saliente con patrón de descarga masiva desde servidor C&C (173 KB de respuesta sobre solo 149 B de petición). Comportamiento típico de bot recogiendo payload desde servidor de comando y control.'),

    (2, 2, 3,
     'Intento repetido de conexión TCP (estado S0, solo SYN enviados) hacia el mismo servidor remoto identificado como C&C. Patrón coherente con heartbeat de bot comprobando disponibilidad del servidor de control.'),

    (3, 3, 0,
     'Consulta NTP estándar (48 B simétricos) a servidor público de hora. Tráfico legítimo de sincronización temporal del dispositivo.'),

    (4, 4, 3,
     'Segunda descarga de gran volumen (172 KB) desde el mismo C&C en pocos segundos. Refuerza la hipótesis de exfiltración de payloads múltiples, compatible con actualización de módulos del bot.'),

    (5, 5, 0,
     'Consulta NTP a servidor europeo. Tamaño y patrón coherentes con sincronización horaria rutinaria.'),

    (6, 6, 0,
     'Consulta NTP benigna. Duración mínima y volumen simétrico de 48 bytes, sin anomalías detectables.'),

    (7, 7, 3,
     'Nueva descarga HTTP de 138 KB desde IP ya identificada como C&C. La persistencia del patrón a lo largo de varios minutos confirma infección activa del dispositivo.'),

    (8, 8, 3,
     'Cuarta descarga consecutiva desde el mismo C&C. La frecuencia e intensidad son consistentes con una botnet IoT en fase de propagación o actualización.');


-- Usuario administrador: El hash se corresponde con la contraseña 'admin'
INSERT INTO usuario (id_usuario, nombre, email, hash_contrasena) VALUES
    (1, 'Administrador', 'administrador@uoc.edu',
     '$2a$11$G9swRtCEgySao8LYsfTb9.pLNo5lWAPqV0jYQtVquH.WayGn9xTly');


-- Reinicio de contadores IDENTITY
ALTER TABLE origen_datos   ALTER COLUMN id_origen_datos   RESTART WITH 2;
ALTER TABLE registro       ALTER COLUMN id_registro       RESTART WITH 13;
ALTER TABLE clasificacion  ALTER COLUMN id_clasificacion  RESTART WITH 9;
ALTER TABLE usuario        ALTER COLUMN id_usuario        RESTART WITH 2;
