-- Tablas y datos de muestra.

-- Módulo Registros
CREATE TABLE origen_datos (
    id_origen_datos   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              INTEGER NOT NULL CHECK (tipo IN (0, 1)),
    nombre            VARCHAR(100) NOT NULL,
    UNIQUE (tipo, nombre)
);

CREATE TABLE registro (
    id_registro       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha             TIMESTAMPTZ NOT NULL,
    ip_origen         VARCHAR(45) NOT NULL,
    ip_destino        VARCHAR(45),
    datos             JSONB NOT NULL,
    estado            INTEGER NOT NULL,
    id_origen_datos   INTEGER NOT NULL,
    hash_registro     VARCHAR(64) NOT NULL UNIQUE,


    CONSTRAINT fk_registro_origen_datos
        FOREIGN KEY (id_origen_datos)
        REFERENCES origen_datos(id_origen_datos)
        ON DELETE RESTRICT
);

CREATE TABLE clasificacion (
    id_clasificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro       INTEGER NOT NULL UNIQUE,
    tipo_trafico      INTEGER NOT NULL,
    justificacion     TEXT NOT NULL,

    CONSTRAINT fk_clasificacion_registro
        FOREIGN KEY (id_registro)
        REFERENCES registro(id_registro)
        ON DELETE CASCADE
);


-- Módulo Usuarios
CREATE TABLE usuario (
    id_usuario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(100) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    hash_contrasena   VARCHAR(255) NOT NULL
);

-- Usuario administrador: El hash se corresponde con la contraseña 'admin'
INSERT INTO usuario (id_usuario, nombre, email, hash_contrasena) VALUES
    (1, 'Administrador', 'administrador@uoc.edu',
     '$2a$11$G9swRtCEgySao8LYsfTb9.pLNo5lWAPqV0jYQtVquH.WayGn9xTly');


-- Reinicio de contadores IDENTITY
ALTER TABLE origen_datos   ALTER COLUMN id_origen_datos   RESTART WITH 2;
ALTER TABLE usuario        ALTER COLUMN id_usuario        RESTART WITH 2;
